name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Zig Test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: mlugg/setup-zig@v2
      - name: Run Zig Tests
        run: zig build test
